name: Deploy Flask API to Azure (No Docker)

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

env:
  AZURE_WEBAPP_NAME: tvsmazoogappsbx03-ds-svcmateai # <<-- Replace with your Azure Web App name
  AZURE_RESOURCE_GROUP: tvsmazoogrsgsbx01-ds-svcmateai # <<-- Replace with your Azure Resource Group name
  PYTHON_VERSION: '3.10' # <<-- Ensure this matches your Flask app's Python version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    # Optional: Install dependencies in the runner (Azure App Service does this too)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: . # Deploys the entire current directory